import Layout from '@/components/layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/animated-profile-pic.png'
import AnimatedText from '@/components/animatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/icons'

export default function Home() {
  return (
    <>
      <Head>
        <title>unlessDev</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2'>
              <Image src={profilePic} alt="unlessDev" className='w-full h-auto ' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Un desarrollador convierte café en código." className='!text-5xl !text-left' />
              <p className='my-4 text-base font-medium'>
              Desarrollador Full-Stack con experiencia en React.js. Apasionado, dedicado y positivo. 
              Si quieres conocer más sobre mi trabajo, ¡visita este sitio!
              </p>

              <div className='flex items-center self-start mt-2'>
                <Link href="/curriculum.pdf" target={"_blank"}
                className='flex items-center bg-dark text-light 
                            p-2.5 px-6 rounded-xl text-lg font-semibold 
                            hover:bg-blue-400 hover:text-dark border-2 
                             border-solid border-transparent hover:border-black'
                download={true}
                >Resumen<LinkArrow className={"w-6 ml-1"} />
                </Link>

                <Link href="mailto:info@unlessdev.com.ar" target={"_blank"}
                className='ml-4 text-lg font-medium capitalize text-dark underline hover:text-blue-400'
                >Contáctame</Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
